// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm2s9z7ZX17k16-R3OYzxoof1W5o4dsTI',
    appId: '1:1052053466001:android:1ebc39785190d558cac830',
    messagingSenderId: '1052053466001',
    projectId: 'gallery-9900a',
    storageBucket: 'gallery-9900a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlo83lrW5-48TuHKLHBc49gAfdIzfHqc4',
    appId: '1:1052053466001:ios:5e88ca639568aeedcac830',
    messagingSenderId: '1052053466001',
    projectId: 'gallery-9900a',
    storageBucket: 'gallery-9900a.appspot.com',
    iosClientId: '1052053466001-k2f2qrlpq9rhmqelh9ab67tk5eq4pv7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.gallery',
  );
}
